<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Taxa;
use Illuminate\Support\Facades\DB;

class UNALLaPazCatalogSeeder extends Seeder
{
    /**
     * Atribución bibliográfica de la fuente principal de datos.
     */
    protected string $attribution = 'Acevedo-Quintero, J. F., & Zamora-Ábrego, J. G. (2022). Inventario de mamíferos asociados al campus universitario de la Universidad Nacional de Colombia - Sede de La Paz, Cesar. Mammalogy Notes, 7(2), 298. https://doi.org/10.47603/mano.v7n2.298';

    /**
     * Mamíferos catalogados en el campus UNAL Sede La Paz (Cesar, Colombia).
     * Fuente: Acevedo-Quintero & Zamora-Ábrego (2022).
     */
    protected array $species = [
        [
            'scientific_name'    => 'Didelphis marsupialis',
            'common_name'        => 'Zarigüeya',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Didelphimorpha',
            'family'             => 'Didelphidae',
            'genus'              => 'Didelphis',
            'species'            => 'marsupialis',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Linnaeus, 1758',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 19,
        ],
        [
            'scientific_name'    => 'Marmosa robinsoni',
            'common_name'        => 'Marmosa',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Didelphimorpha',
            'family'             => 'Didelphidae',
            'genus'              => 'Marmosa',
            'species'            => 'robinsoni',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Bangs, 1898',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 18,
        ],
        [
            'scientific_name'    => 'Myrmecophaga tridactyla',
            'common_name'        => 'Oso palmero',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Pilosa',
            'family'             => 'Myrmecophagidae',
            'genus'              => 'Myrmecophaga',
            'species'            => 'tridactyla',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Linnaeus, 1758',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 18,
        ],
        [
            'scientific_name'    => 'Tamandua mexicana',
            'common_name'        => 'Oso hormiguero',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Pilosa',
            'family'             => 'Myrmecophagidae',
            'genus'              => 'Tamandua',
            'species'            => 'mexicana',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Saussure, 1860',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 26,
        ],
        [
            'scientific_name'    => 'Molossus molossus',
            'common_name'        => 'Murciélago mastín',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Chiroptera',
            'family'             => 'Molossidae',
            'genus'              => 'Molossus',
            'species'            => 'molossus',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Pallas, 1766',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 1,
        ],
        [
            'scientific_name'    => 'Pteronotus rubiginosus',
            'common_name'        => 'Murciélago',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Chiroptera',
            'family'             => 'Mormoopidae',
            'genus'              => 'Pteronotus',
            'species'            => 'rubiginosus',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Wagner, 1843',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 1,
        ],
        [
            'scientific_name'    => 'Noctilio albiventris',
            'common_name'        => 'Murciélago pescador',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Chiroptera',
            'family'             => 'Noctilionidae',
            'genus'              => 'Noctilio',
            'species'            => 'albiventris',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Desmarest, 1818',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 4,
        ],
        [
            'scientific_name'    => 'Artibeus jamaicensis',
            'common_name'        => 'Murciélago frutero',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Chiroptera',
            'family'             => 'Phyllostomidae',
            'genus'              => 'Artibeus',
            'species'            => 'jamaicensis',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Leach, 1821',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 5,
        ],
        [
            'scientific_name'    => 'Glossophaga soricina',
            'common_name'        => 'Murciélago trompón',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Chiroptera',
            'family'             => 'Phyllostomidae',
            'genus'              => 'Glossophaga',
            'species'            => 'soricina',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Pallas, 1766',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 39,
        ],
        [
            'scientific_name'    => 'Phyllostomus discolor',
            'common_name'        => 'Murciélago',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Chiroptera',
            'family'             => 'Phyllostomidae',
            'genus'              => 'Phyllostomus',
            'species'            => 'discolor',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Wagner, 1843',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 1,
        ],
        [
            'scientific_name'    => 'Sturnira cf parvidens',
            'common_name'        => 'Murciélago',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Chiroptera',
            'family'             => 'Phyllostomidae',
            'genus'              => 'Sturnira',
            'species'            => 'cf parvidens',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Goldman, 1917',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 1,
        ],
        [
            'scientific_name'    => 'Cerdocyon thous',
            'common_name'        => 'Zorro Perro',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Carnivora',
            'family'             => 'Canidae',
            'genus'              => 'Cerdocyon',
            'species'            => 'thous',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Linnaeus, 1766',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 69,
        ],
        [
            'scientific_name'    => 'Herpailurus yagouaroundi',
            'common_name'        => 'Yaguarundí',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Carnivora',
            'family'             => 'Felidae',
            'genus'              => 'Herpailurus',
            'species'            => 'yagouaroundi',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'É. Geoffroy Saint-Hilaire, 1803',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 36,
        ],
        [
            'scientific_name'    => 'Leopardus pardalis',
            'common_name'        => 'Ocelote',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Carnivora',
            'family'             => 'Felidae',
            'genus'              => 'Leopardus',
            'species'            => 'pardalis',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Linnaeus, 1758',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 9,
        ],
        [
            'scientific_name'    => 'Procyon cancrivorus',
            'common_name'        => 'Mapache',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Carnivora',
            'family'             => 'Procyonidae',
            'genus'              => 'Procyon',
            'species'            => 'cancrivorus',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'G.[E.] Cuvier, 1798',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 45,
        ],
        [
            'scientific_name'    => 'Conepatus semistriatus',
            'common_name'        => 'Mapurito',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Carnivora',
            'family'             => 'Mephitidae',
            'genus'              => 'Conepatus',
            'species'            => 'semistriatus',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Boddaert, 1784',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 22,
        ],
        [
            'scientific_name'    => 'Galictis vittata',
            'common_name'        => 'Hurón',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Carnivora',
            'family'             => 'Mustelidae',
            'genus'              => 'Galictis',
            'species'            => 'vittata',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Schreber, 1776',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 2,
        ],
        [
            'scientific_name'    => 'Zygodontomys sp.',
            'common_name'        => 'Ratón',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Rodentia',
            'family'             => 'Cricetidae',
            'genus'              => 'Zygodontomys',
            'species'            => 'sp.',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Allen, 1897',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 1,
        ],
        [
            'scientific_name'    => 'Cabassous centralis',
            'common_name'        => 'Armadillo coletrapo',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Cingulata',
            'family'             => 'Chlamyphoridae',
            'genus'              => 'Cabassous',
            'species'            => 'centralis',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Miller, 1899',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 5,
        ],
        [
            'scientific_name'    => 'Dasypus novemcinctus',
            'common_name'        => 'Armadillo común',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Cingulata',
            'family'             => 'Dasypodidae',
            'genus'              => 'Dasypus',
            'species'            => 'novemcinctus',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Linnaeus, 1758',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 12,
        ],
        [
            'scientific_name'    => 'Sylvilagus sp.',
            'common_name'        => 'Conejo',
            'kingdom'            => 'Animalia',
            'phylum'             => 'Chordata',
            'class'              => 'Mammalia',
            'order_name'         => 'Lagomorpha',
            'family'             => 'Leporidae',
            'genus'              => 'Sylvilagus',
            'species'            => 'sp.',
            'conservation_status'=> null,
            'is_native'          => null,
            'is_endemic'         => null,
            'taxon_author'       => 'Gray, 1867',
            'inventory_author'   => 'Acevedo-Quintero y Zamora-Ábrego (2022)',
            'local_records_count'=> 62,
        ],
    ];

    public function run(): void
    {
        // Eliminar registros previos y reiniciar el autoincremento
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('taxon_api_references')->truncate();
        DB::table('taxa')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $this->command->info('Tabla taxa vaciada. Insertando catálogo de mamíferos UNAL La Paz...');

        foreach ($this->species as $data) {
            Taxa::create(array_merge($data, [
                'attribution' => $this->attribution,
            ]));
        }

        $this->command->info('✅ ' . count($this->species) . ' especies insertadas correctamente.');
    }
}
